name: .NET

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Define jobs that run on Ubuntu runner
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Set up .NET Core SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x' # or specify your required .NET version
    
    # Restore NuGet packages
    - name: Restore dependencies
      run: dotnet restore
    
    # Build the project
    - name: Build the project
      run: dotnet build --configuration Release --no-restore
    
    # Run tests (if applicable)
    - name: Run tests
      run: dotnet test --no-build --verbosity normal
    
    # Publish the project (creates publish artifacts)
    - name: Publish application
      run: dotnet publish -c Release -o ./publish

  # Deploy job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Deploy your application (example uses FTP)
    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./publish
        server-dir: /path/to/deployment/directory
